# Site settings
title: "APP TITLE"
email: app@app.com
company: "APP COMPANY INFO"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://app.com" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
highlighter: pygments # or rouge or null
permalink: pretty

# Exclude
exclude: ["node_modules", "gulpfile.js", "package.json", "apps/**/*.scss"]